graphql:
    tools:
        schema-location-pattern: "graphql/*.graphqls"
    servlet:
        mapping: /graphql
        enabled: true
        corsEnabled: false
        # if you want to @ExceptionHandler annotation for custom GraphQLErrors
        exception-handlers-enabled: true
        contextSetting: PER_REQUEST_WITH_INSTRUMENTATION

graphiql:
    mapping: /graphiql
    endpoint:
        graphql: /graphql
        subscriptions: /subscriptions
    subscriptions:
        timeout: 30
        reconnect: false
    static:
        basePath: /
    enabled: true
    pageTitle: GraphiQL
    props:
        variables:
            editorTheme: "solarized light"